let questions = [
    {
        "question":"今天的心情怎麼樣？",
        "answers":[
            ["很好",2],
            ["一般",3],
            ["不好",4]
        ]
    },
    {
        "question":"為什麼開心？",
        "answers":[
            ["戀愛的粉紅泡泡",5],
            ["平淡日子的小幸福",6],
            ["沒有為什麼",6]
        ]
    },
    {
        "question":"為什麼一般？",
        "answers":[
            ["無聊",7],
            ["過的平平淡淡",7],
            ["不知道ㄟ",7]
        ]
    },
    {
        "question":"為什麼傷心？",
        "answers":[
            ["好寂寞",8],
            ["失戀ㄌ",8],
            ["考試考砸了",9]
        ]
    },
    {
        "question":"聽首歌吧<3",
        "answers":[
            ["go!","A"]
        ]
    },
    {
        "question":"聽首歌吧~",
        "answers":[
            ["go!","B"]
        ]
    },
    {
        "question":"聽首歌吧",
        "answers":[
            ["go!","C"]
        ]
    },
    {
        "question":"聽首歌吧 cheer up",
        "answers":[
            ["go!","D"]
        ]
    },
    {
        "question":"聽首歌吧!!",
        "answers":[
            ["go!","E"]
        ]
    }
    
];

let finalAnswers={
        "A":["-IZmsDozPLU"],
        "B":["8l2orzWG1qU"],
        "C":["Ts5ZiojkOe4"],
        "D":["AMzjbyZhM5U"],
        "E":["IeqtfdcyvW0"]
};

